language: php
php:
- 7.0
- 7.1
before_script:
- composer install --no-interaction
script:
- vendor/bin/phpunit
notifications:
  email: false
  slack:
    secure: Z/oqcQ819DIUfdaLTTIyXJ5lRXnuiWj+9xcz3mA3MdmQ717k3SH6QXoZW7zQqciIqzquuvSL7rdeC+4oPVg90PLYK19Lv9KehVpdz4v0FgDWo5SxkPLMcNXKMNIJ/t6maDG23JofgRYa23dt4/tLC+qNir5/uC2Jep+TqQOn6UB+SFcAVyY275vujecTahCTi4TsWZcNWZjOG29sq152O3dh04vHqP5dBOcf5x2s0ASlg1FB9moXXvZFcsIlbml8bGHVEP3SAfDayabq4CeB1e6R2l9Sy5NGAtB/8D44OIVyvbas2Tu/IDOfkH0CkDE9pjWqeCJmzIwrhV0PgdtQ/wuSf+FpOnJENaEYFNi35oYx2dEcFO9O1DVCBwLJ3bgGrFbC8FraU5VUaxuYk1kbPgySl1fqyc/oyXmLOPqHlxN2TXLpU5rQHksBgY2dXp1GtPuFUYu7yLoNchxCpTuoYbB8YnK2PmZk6q2ndwmnVdTx4Xr1EnrNcG8rcOhj+thH8Tvr27emNt8PUKxw5AOojR4g+TCJ5KM85G1FRKNIM10H5q0eB16kMEqqwhFuwYYjmIRJ0PEN8uI/7vSwR0fJDZowEP7IaGuYgZVBPJdxOU1Vf5y/ysXHRJ4e2Eupxb1VcF/BOWRShLqbCe8t22rteD9fheXU2BlSxQuDDVP1NsU=
